# Use root/example user/password credentials
version: '3.1'

services:
  # The following code creates a container named 'php' that runs the 'php:7.4-apache' image from the Docker Hub on port 80, mounting the source directory to /var/www/html.
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
